apiVersion: v1
kind: Service
metadata:
  name: seoul
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
metadata:
  name: express
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: seoul,express
  type: LoadBalancer
